version: 3

silent: true

dotenv:
  - .env

vars:
  DOCKER_TAG: dev/bun-api-server

includes:
  test: Taskfile.tests.yaml

tasks:
  dev:
    cmds:
      - bun run dev

  compile:
    cmds:
      - bun run compile

  check:
    cmds:
      - bun run check

  verify:
    cmds:
      - bun run verify

  docker-build:
    cmds:
      - docker build --pull -t {{.DOCKER_TAG}} --progress plain .

  docker-run:
    cmds:
      - docker run --rm -p 3000:3000 {{.DOCKER_TAG}}

  docker-push:
    cmds:
      - docker push {{.DOCKER_TAG}}
