version: 3

silent: true

vars:
  DOCKER_TAG: dev/bun-api-server

env:
  #PORT: 3333
  OPENAI_API_KEY: sk-USE-YOUR-OWN-API-KEY

includes:
  test: Taskfile.tests.yaml

tasks:
  dev:
    cmds:
      - bun run --watch src/index.ts

  compile:
    cmds:
      - |
        # get app name from package.json with jq
        APP_NAME=$(jq -r '.name' package.json)
        bun run build-routes.ts
        bun build src/index.ts --compile --outfile "dist/${APP_NAME}"

  docker-build:
    cmds:
      - docker build -t {{.DOCKER_TAG}} --progress plain --no-cache .

  docker-run:
    cmds:
      - docker run -d -it --rm -p 3000:3000 -e OPENAI_API_KEY={{.OPENAI_API_KEY}} {{.DOCKER_TAG}}

  docker-push:
    cmds:
      - docker push {{.DOCKER_TAG}}

