server:
  port: 3000
  cors:
    enabled: true
    allowedOrigins: ["http://localhost:3000"]
    allowedMethods: ["GET", "POST", "PUT", "DELETE"]
    allowedHeaders: ["Content-Type", "Authorization"]
    exposedHeaders: ["Authorization"]
    allowCredentials: true
    maxAge: 300